version: '3.9'
services:
  mysql:
    container_name: mysql
    image: "mysql"
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/home/mysql-data:/var/lib/mysql'
    networks:
      - my-network      
  eureka:
    build:
      context: ../services/eurekaServer
      dockerfile: Dockerfile
    image: eureka
    container_name: eureka
    restart: "on-failure"
    ports:
      - "8761:8761"
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    networks:
      - my-network
  spring_app:
    build:
      context: ../services/microservicesUser
      dockerfile: Dockerfile
    image: "msuser"
    container_name: msuser
    restart: "on-failure"
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    networks:
      - my-network
networks:
  my-network:


      
