version: '3.9'
services:
  mysql:
    container_name: mysql
    image: "mysql"
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/home/mysql-data:/var/lib/mysql'
    networks:
      - my-network      
  eureka:
    build:
      context: ../backend/eurekaServer
      dockerfile: Dockerfile
    image: eureka
    container_name: eureka
    restart: "on-failure"
    ports:
      - "8761:8761"
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    networks:
      - my-network
  gatwayapi:
    build:
      context: ../backend/gatewayAPI
      dockerfile: Dockerfile
    image: gatewayapi
    container_name: gatewayapi
    restart: "on-failure"
    ports:
      - "8000:8000"
    depends_on:
      - eureka
    environment:
      - spring.cloud.gateway.routes[0].id=user-microservice-route
      - spring.cloud.gateway.routes[0].uri=http://userserive:8081
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
      - logging.level.root=INFO
      - logging.level.org.springframowrk.cloud.gateway.route.RouteDefinitionLocator = INFO
      - logging.level.org.springframowrk.cloud.gateway= TRACE
      - eureka.client.serviceUrl.defaultZone= http://eureka:8761/eureka/
    networks:
      - my-network
  userserive:
    build:
      context: ../backend/services/user-service
      dockerfile: Dockerfile
    image: "userserive"
    container_name: userserive
    restart: "on-failure"
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    networks:
      - my-network
networks:
  my-network:


      
