version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: "on-failure"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ms_user_db
    ports:
      - "5432:5432"
    volumes:
      - '/home/postgres-data:/var/lib/postgresql/data'
  eureka-service:
    image: eureka-service
    container_name: eureka-service
    restart: "on-failure"
    ports:
      - "8761:8761"
    environment:
      - eureka.client.register-with-eureka=true
      - eureka.client.eureka-server-u-r-l-context=http://eureka-service:8761/eureka-service
  spring_app:
    image: "msuser"
    container_name: msuser
    restart: "on-failure"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - eureka-service